# -*- coding: utf-8 -*-
"""Kmeans_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CgIDAgT5Kr4tli_TdvvInKkahcDQhgfi
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans

st.set_page_config(
    page_title="K-Means Clustering",
    page_icon="📊",
    layout="centered"
)

st.title("📊 K-Means Clustering")
st.write("Cluster data using the K-Means Algorithm.")

# Load Dataset

df = pd.read_csv("income.csv")

st.subheader("Dataset")

st.dataframe(df)

# Train Model

X = df[['Age', 'Income($)']]

km = KMeans(n_clusters=3, random_state=42)

y_predicted = km.fit_predict(X)

df['Cluster'] = y_predicted

#User Input

st.subheader("Enter Details")

age = st.number_input(
    "Age",
    min_value=1,
    max_value=100,
    value=30
)

income = st.number_input(
    "Income",
    min_value=1000,
    value=50000
)

if st.button("Predict Cluster"):

    cluster = model.predict([[age, income]])

    st.success(f"This person belongs to Cluster {cluster[0]}")

    fig, ax = plt.subplots(figsize=(8,6))

ax.scatter(
    df['Age'],
    df['Income($)'],
    c=model.labels_,
    cmap='viridis'
)

ax.set_xlabel("Age")
ax.set_ylabel("Income")

st.pyplot(fig)

st.subheader("Cluster Centers")

centers = pd.DataFrame(
    model.cluster_centers_,
    columns=['Age','Income']
)

st.dataframe(centers)

st.subheader("Model Details")

st.write("Number of Clusters:", model.n_clusters)

st.write("Inertia:", model.inertia_)

st.write("Cluster Centers:")

st.write(model.cluster_centers_)

